# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pi/Pi0W

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pi/Pi0W

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/Pi0W/CMakeFiles /home/pi/Pi0W/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/Pi0W/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Bike

# Build rule for target.
Bike: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Bike
.PHONY : Bike

# fast build rule for target.
Bike/fast:
	$(MAKE) -f CMakeFiles/Bike.dir/build.make CMakeFiles/Bike.dir/build
.PHONY : Bike/fast

src/Audio.o: src/Audio.c.o

.PHONY : src/Audio.o

# target to build an object file
src/Audio.c.o:
	$(MAKE) -f CMakeFiles/Bike.dir/build.make CMakeFiles/Bike.dir/src/Audio.c.o
.PHONY : src/Audio.c.o

src/Audio.i: src/Audio.c.i

.PHONY : src/Audio.i

# target to preprocess a source file
src/Audio.c.i:
	$(MAKE) -f CMakeFiles/Bike.dir/build.make CMakeFiles/Bike.dir/src/Audio.c.i
.PHONY : src/Audio.c.i

src/Audio.s: src/Audio.c.s

.PHONY : src/Audio.s

# target to generate assembly for a file
src/Audio.c.s:
	$(MAKE) -f CMakeFiles/Bike.dir/build.make CMakeFiles/Bike.dir/src/Audio.c.s
.PHONY : src/Audio.c.s

src/Video.o: src/Video.c.o

.PHONY : src/Video.o

# target to build an object file
src/Video.c.o:
	$(MAKE) -f CMakeFiles/Bike.dir/build.make CMakeFiles/Bike.dir/src/Video.c.o
.PHONY : src/Video.c.o

src/Video.i: src/Video.c.i

.PHONY : src/Video.i

# target to preprocess a source file
src/Video.c.i:
	$(MAKE) -f CMakeFiles/Bike.dir/build.make CMakeFiles/Bike.dir/src/Video.c.i
.PHONY : src/Video.c.i

src/Video.s: src/Video.c.s

.PHONY : src/Video.s

# target to generate assembly for a file
src/Video.c.s:
	$(MAKE) -f CMakeFiles/Bike.dir/build.make CMakeFiles/Bike.dir/src/Video.c.s
.PHONY : src/Video.c.s

src/main.o: src/main.c.o

.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) -f CMakeFiles/Bike.dir/build.make CMakeFiles/Bike.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) -f CMakeFiles/Bike.dir/build.make CMakeFiles/Bike.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) -f CMakeFiles/Bike.dir/build.make CMakeFiles/Bike.dir/src/main.c.s
.PHONY : src/main.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Bike"
	@echo "... src/Audio.o"
	@echo "... src/Audio.i"
	@echo "... src/Audio.s"
	@echo "... src/Video.o"
	@echo "... src/Video.i"
	@echo "... src/Video.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

